In [2]:
a = {1, 2, 3, 4, 5, 5}
print(a)
print(type(a))

{1, 2, 3, 4, 5}
<class 'set'>


In [3]:
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x
print(x is z)
print("x id is ", id(x))
print("y id is ", id(y))
print("z id is ", id(z))

True
x id is  5100394112
y id is  4356509120
z id is  5100394112


In [4]:
a = 'prashant'
print(a)
print(id(a))
a = a+" joshi"
print(a)
print(id(a))
b = type(a[0])
print(type(b))

prashant
4356838448
prashant joshi
4356839664
<class 'type'>


In [5]:
name = "i am python developer"
print(name)
print("name[2:4]", name[2:4])
print("name[5:9]", name[5:9])
print("name[:15]", name[:15])
print("name[2:]", name[2:])
print("name[:]", name[:])
print("name[0:17:3]", name[0:17:3])
print("name[:]", name[::])
print("name[::-1]", name[::-1])
str = name.capitalize()
str1 = name.center(30)
print(str)
print(str1)

str2 = name.count("e", 6, 15)
print(str2)

i am python developer
name[2:4] am
name[5:9] pyth
name[:15] i am python dev
name[2:] am python developer
name[:] i am python developer
name[0:17:3] imyode
name[:] i am python developer
name[::-1] repoleved nohtyp ma i
I am python developer
    i am python developer     
1


In [6]:
str = "hello this is python class."
isends = str.endswith(".")
print(isends)

isends = str.endswith("is", 0, 13)
print(isends)

isends = str.startswith("is", 8, 56)
print(isends)

isends = str.find("x", 15, 25)  # not found return -1
print(isends)

isends = str.index("th", 15, 25)  # not found return error
print(isends)

isends = str.isalnum()

if str.isalpha() == True:
    print("String contains alphabets")

else:
    print("String contains other chars too")


str2 = str.islower()
print(str2)
str2 = str.isupper()
print(str2)

str.upper()
print(str)
str2 = str.upper()
print(str2)

str2 = " 50 "
str2 = str2.isnumeric()
print(str2)

str = "***python***"
str2 = str.lstrip("*")
str3 = str.rstrip("*")
str4 = str.strip("*")

print(str2)
print(str3)
print(str4)

str = "java is a java programming java language java"
str2 = str.replace("java", "c", 2)
print(str2)

True
True
True
-1
16
String contains other chars too
True
False
hello this is python class.
HELLO THIS IS PYTHON CLASS.
False
python***
***python
python
c is a c programming java language java


In [7]:
str = "Python123 swapcase() method converts"


def countChars(str):
    al = 0
    num = 0
    spe = 0
    sum = 0

    for i in str:
        if i.isalpha():
            al += 1
        elif i.isnumeric():
            num += 1
            sum += int(i)
        else:
            spe += 1
    return [al, num, spe, sum]


a = countChars(str)
print(f'Total number of alphabets : {a[0]}')
print(f'Total number of numeric : {a[1]}')
print(f'Total number of special characters : {a[2]}')
print(f'Total sum of numeric : {a[3]}')

Total number of alphabets : 28
Total number of numeric : 3
Total number of special characters : 5
Total sum of numeric : 6


In [8]:
def removeKeys(dict):
    a = []
    for keys in dict:
        a.append(dict[keys])

    return a


dict = {"name": "prashant", "age": 21, "city": "noida"}
a = removeKeys(dict)
print(a)

['prashant', 21, 'noida']


In [9]:
print("line 1")
print("line 2")
print("line 3")
print("line 4")
try:
    print('hi')
    print(10/0)
    print(name)
except:
    print("Something went wrong")
else:
    print("else block")
finally:
    print("finally block")
print("line 5")

line 1
line 2
line 3
line 4
hi
Something went wrong
finally block
line 5


In [10]:
def validAge(age):
    if (age >= 18):
        print("The age is valid")
    else:
        raise ValueError("hi")


try:
    validAge(17)
except ValueError as e:
    print("The age is not valid", e)

The age is not valid hi


In [11]:
import numpy as np

a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(a.ndim)
print(a.shape)

3
(2, 2, 3)


In [12]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x = a.view()
b = a
y = a.copy()
print(id(a), id(b), id(x), id(y))
b[0] = 42
print(x, a, b, y)

5100898704 5100898704 5100542384 5100541808
[42  2  3  4  5  6  7  8  9] [42  2  3  4  5  6  7  8  9] [42  2  3  4  5  6  7  8  9] [1 2 3 4 5 6 7 8 9]


In [13]:
arr = np.array([10, 20, 30, 40, 50])
arr2 = arr[1:4]
print(arr)
print(arr2)
arr[1] = 100
print(arr+9)
print(arr2)

x = arr.copy()
arr[0] = 100

[10 20 30 40 50]
[20 30 40]
[ 19 109  39  49  59]
[100  30  40]


In [14]:
arr = np.zeros((5, 3), dtype=int)+9
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]


In [15]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute the dot product
dot_product = np.dot(A, B)
# or using the @ operator
dot_product_at = A @ B

print("Dot product using np.dot():\n", dot_product)
print("Dot product using @ operator:\n", dot_product_at)
print(A*B)

random = np.random.rand(3, 2)
print(random)

arr = np.random.randint(1, 100, 20)
arr = arr.reshape(-1, 4)
print(arr)
arr = arr.reshape(4, -1)
print(arr)

np.random.seed(111)
arr = np.random.randint(1, 500, 30).reshape(6, 5)
print(arr)
print(arr[2:, 2:])
print(arr[3:5, 2:4])
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
slicing = ar[4:9]
slicing[:] = 0
print(slicing)
print(ar)

Dot product using np.dot():
 [[19 22]
 [43 50]]
Dot product using @ operator:
 [[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[0.44290157 0.54009385]
 [0.61312783 0.47710105]
 [0.80024717 0.99637504]]
[[76 52 40 75]
 [71 42 47 70]
 [72  1 61 68]
 [29 49 34 17]
 [32 28 15 74]]
[[76 52 40 75 71]
 [42 47 70 72  1]
 [61 68 29 49 34]
 [17 32 28 15 74]]
[[341 365 469 213  87]
 [276 170 323 119 467]
 [297 456 442   8 269]
 [267 450 369 217 285]
 [271 419  22  55 201]
 [ 38 461 231 187 269]]
[[442   8 269]
 [369 217 285]
 [ 22  55 201]
 [231 187 269]]
[[369 217]
 [ 22  55]]
[0 0 0 0 0]
[ 1  2  3  4  0  0  0  0  0 10]


In [16]:
import numpy as np

# Example data: Exam scores of students in different subjects
exam_scores = np.array([
    [85, 90, 78, 92, 88, 95, 77, 80, 82, 65],
    [70, 68, 88, 95, 92, 72, 75, 95, 92, 92],
    [96, 68, 70, 75, 88, 85, 89, 78, 82, 80]
])

# Calculate the average score of each student
average_scores = np.mean(exam_scores, axis=1)

print("Exam Scores:\n", exam_scores)
print("Average Scores:", average_scores)

Exam Scores:
 [[85 90 78 92 88 95 77 80 82 65]
 [70 68 88 95 92 72 75 95 92 92]
 [96 68 70 75 88 85 89 78 82 80]]
Average Scores: [83.2 83.9 81.1]


In [17]:
import numpy as np

# Example data: Temperature data for a week (7 days) in Celsius
temperature_data = np.array([25, 28, 22, 26, 24, 27, 23])

# Perform slicing: Get temperatures for the first three days
first_three_days = temperature_data[:3]

# Perform indexing: Get the temperature of the fourth day
fourth_day_temp = temperature_data[3]

# Reshape the array: Convert 1D array to 2D array (1 week of temperatures, 1 temperature per day)
reshaped_data = temperature_data.reshape(7, 1)

# Calculate statistics: Mean, Median, Standard Deviation
mean_temp = np.mean(temperature_data)
median_temp = np.median(temperature_data)
std_dev_temp = np.std(temperature_data)

print("Temperature Data for a Week:", temperature_data)
print("First Three Days Temperatures:", first_three_days)
print("Fourth Day Temperature:", fourth_day_temp)
print("Reshaped Data:\n", reshaped_data)
print("Mean Temperature:", mean_temp)
print("Median Temperature:", median_temp)
print("Standard Deviation of Temperature:", std_dev_temp)

Temperature Data for a Week: [25 28 22 26 24 27 23]
First Three Days Temperatures: [25 28 22]
Fourth Day Temperature: 26
Reshaped Data:
 [[25]
 [28]
 [22]
 [26]
 [24]
 [27]
 [23]]
Mean Temperature: 25.0
Median Temperature: 25.0
Standard Deviation of Temperature: 2.0


In [22]:
ar = np.arange(1,15)
print(ar)
print(ar[ar%2==0])
print(ar[ar%2!=0])  
print(ar[ar>8])
ar[ar%2==0]=0
print(ar)

arr = np.arange(1,8)
print(arr+2)
print(arr*2)
print(arr**2)

arr = np.array([10,20,30,25,6,2])
print(arr)
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))

np.random.seed(122)
mat = np.random.randint(1,21,9).reshape(3,3)
print(mat)
print(np.sum(mat))
print(np.cumsum(mat))
print(np.min(mat))
print(np.max(mat))
print("------------------------")
print(np.sum(mat,axis=1))
print(np.min(mat,axis=1))
print(np.max(mat,axis=1))
print(np.cumsum(mat,axis=1))


def cumsum(mat):
    arr = np.array([],dtype=int)
    sum = 0
    
    for row in mat:
        for i in row:
            sum += i
            arr = np.append(arr,sum)
    return arr

mat = np.array([[16, 11 ,13],[17 ,13 ,16],[ 3 ,16 ,11]])
arr = cumsum(mat)
print(arr)

np.random.shuffle(mat)
print(mat)
print(np.unique(mat,return_index=True,return_counts=True))
print(np.unique(mat).size)

np.random.seed(122)
mat1 = np.random.randint(1,21,9).reshape(3,3)
mat2 = np.random.randint(50,71,9).reshape(3,3)
print(mat1)
print(mat2)
print(np.vstack((mat1,mat2)))
print(np.hstack((mat1,mat2)))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
[ 1  3  5  7  9 11 13]
[ 9 10 11 12 13 14]
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]
[3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]
[10 20 30 25  6  2]
2
30
5
2
[3.16227766 4.47213595 5.47722558 5.         2.44948974 1.41421356]
[-0.54402111  0.91294525 -0.98803162 -0.13235175 -0.2794155   0.90929743]
[-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.41614684]
[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
116
[ 16  27  40  57  70  86  89 105 116]
3
17
------------------------
[40 46 30]
[11 13  3]
[16 17 16]
[[16 27 40]
 [17 30 46]
 [ 3 19 30]]
[ 16  27  40  57  70  86  89 105 116]
[[16 11 13]
 [ 3 16 11]
 [17 13 16]]
(array([ 3, 11, 13, 16, 17]), array([3, 1, 2, 0, 6]), array([1, 2, 2, 3, 1]))
5
0.1569918378916666
[[60 62 66]
 [62 65 52]
 [65 60 59]]


In [46]:
arr = np.array([1,2,4,6,7,8,9,5,10,3])
np.searchsorted(arr,[3,5,10])

array([2, 3, 8])