In [1]:
import numpy as np
import pandas as pd
temperatures = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2])

print("Hot Days:")
print("Day   temperatures")
for i in range(len(temperatures)):
    if temperatures[i] > 35:
        print(f"{i+1}     {temperatures[i]}")
print("\nCold Days:")
print("Day   temperatures")
for i in range(len(temperatures)):
    if temperatures[i] < 5:
        print(f"{i+1}     {temperatures[i]}")



Hot Days:
Day   temperatures
3     36.8
6     38.7
10     37.2

Cold Days:
Day   temperatures


In [2]:
monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])
quarterly_sales = monthly_sales.reshape(4, 3)

for i in range(len(quarterly_sales)):
    print(f"Quarter {i+1} Sales (in thousands of dollars):\n{quarterly_sales[i]}")

Quarter 1 Sales (in thousands of dollars):
[120 135 148]
Quarter 2 Sales (in thousands of dollars):
[165 180 155]
Quarter 3 Sales (in thousands of dollars):
[168 190 205]
Quarter 4 Sales (in thousands of dollars):
[198 210 225]


In [3]:
customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])
print("Active Customers (Last Purchase) <= 30 days ago")
print(customer_ids[last_purchase_days_ago <= 30])

print("Inactive Customers (Last Purchase) > 30 days ago")
print(customer_ids[last_purchase_days_ago > 30])

Active Customers (Last Purchase) <= 30 days ago
[101 102 103 104 105]
Inactive Customers (Last Purchase) > 30 days ago
[106 107 108 109 110]


In [4]:
# Employee data for full-time employees
full_time_employees = np.array([
[101, 'John Doe', 'Full-Time', 55000],
[102, 'Jane Smith', 'Full-Time', 60000],
[103, 'Mike Johnson', 'Full-Time', 52000]
])
# Employee data for part-time employees
part_time_employees = np.array([
[201, 'Alice Brown', 'Part-Time', 25000],
[202, 'Bob Wilson', 'Part-Time', 28000],
[203, 'Emily Davis', 'Part-Time', 22000]
])

print('Combined Employee Data:')
for employee in full_time_employees:
    print(f'Employee ID: {employee[0]}, Name: {employee[1]}, Type: {employee[2]}, Salary: {employee[3]}')
for employee in part_time_employees:
    print(f'Employee ID: {employee[0]}, Name: {employee[1]}, Type: {employee[2]}, Salary: {employee[3]}')


Combined Employee Data:
Employee ID: 101, Name: John Doe, Type: Full-Time, Salary: 55000
Employee ID: 102, Name: Jane Smith, Type: Full-Time, Salary: 60000
Employee ID: 103, Name: Mike Johnson, Type: Full-Time, Salary: 52000
Employee ID: 201, Name: Alice Brown, Type: Part-Time, Salary: 25000
Employee ID: 202, Name: Bob Wilson, Type: Part-Time, Salary: 28000
Employee ID: 203, Name: Emily Davis, Type: Part-Time, Salary: 22000


In [5]:
list1 = [
np.array([3, 2, 8, 9]),
np.array([4, 12, 34, 25, 78]),
np.array([23, 12, 67])
]
mean  = [np.mean(i) for i in list1]
print('Mean of Each array\n',mean)


Mean of Each array
 [5.5, 30.6, 34.0]


In [32]:
x_odd = np.array([1, 2, 3, 4, 5, 6, 7])
print('Printing the Original array:\n',x_odd)
print('Median of the array that contain odd no of elements\n',np.median(x_odd))

Printing the Original array:
 [1 2 3 4 5 6 7]
Median of the array that contain odd no of elements
 4.0


In [33]:
arr = [20, 2, 7, 1, 34]
print('arr :',arr)  
print('std of arr :',np.std(arr))

arr : [20, 2, 7, 1, 34]
std of arr : 12.576167937809991


In [1]:
import pandas as pd

data = pd.read_csv('house_prices.csv')
house_prices = data['price'].values

average_price = np.mean(house_prices)

high_prices = house_prices[house_prices > average_price]

high_prices_df = pd.DataFrame(high_prices, columns=['price'])
high_prices_df.to_csv('high_prices.csv', index=False)

NameError: name 'np' is not defined