### LAB 1

In [2]:
# 1
import numpy as np
my_list=[1,2,3,4,5]
my_array=np.array(my_list)
print(my_array)

[1 2 3 4 5]


In [3]:
# 2
my_list=[1,2,3,4,5]
my_array=np.array(my_list)
print(my_array)
print("First Element: ",my_array[0])
print("Second Element: ",my_array[1])
my_array = my_array*2
print("Array after doubling each element:\n",my_array)

[1 2 3 4 5]
First Element:  1
Second Element:  2
Array after doubling each element:
 [ 2  4  6  8 10]


In [4]:
# 1
arr_zeros = np.zeros(10)
arr_ones = np.ones(10)
arr_fives = np.ones(10)*5
print("Array of 10 Zeros:\n",arr_zeros)
print("Array of 10 Ones:\n",arr_ones)
print("Array of 10 Fives:\n",arr_fives)

Array of 10 Zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 Ones:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 Fives:
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [5]:
mat = np.arange(2,11).reshape(3,3)
print(mat)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
